openapi: 3.0.0
info:
  title: 'Open Proces Huis'
  description: 'Beheer van je eigen processen binnen OPH'
  version: 0.0.0
paths:
  /processes:
    post:
      operationId: postProcess
      summary: 'Adding a new process to your administrative unit.'
      tags:
        - Processes
      parameters:
        - name: '@id'
          in: body
          description: 'Uri of the process.'
          required: true
          schema:
            type: string
            example: 'http://data.lblod.info/processes/123456789'
        - name: title
          in: body
          description: 'Name for the process.'
          required: true
          schema:
            type: string
            example: 'Facturatie'
        - name: description
          in: body
          description: 'Describe what the process is about.'
          required: false
          schema:
            type: string
            example: 'De officiële factuur wordt gegenereerd op basis van deze gegevens en vervolgens naar de klant verzonden ter betaling, wat de standaardcyclus afsluit.'
        - name: contact
          in: body
          description: 'Email of person that can be contacted about the process.'
          required: false
          schema:
            type: string
            example: 'contact@administrativeUnit.com'
        - name: linkedInventoryProcess
          in: body
          description: 'Inventory process URI that this process is related to.'
          required: false
          schema:
            type: string
            example: 'http://data.lblod.info/conceptual-processes/123456789'
        - name: users
          in: body
          description: 'List of administrative units that are also using this process.'
          required: false
          schema:
            type: array
            example:
              [
                'http://data.lblod.info/id/bestuurseenheden/123456789',
                'http://data.lblod.info/id/bestuurseenheden/987654321',
              ]
        - name: diagrams
          in: body
          description: "List of file URI's that need to be added to this process. For example: bpmn, visio"
          required: false
          schema:
            type: array
            example: ['share://123456789.bpmn', 'share://987654321.bpmn']
        - name: attachments
          in: body
          description: "List of file URI's that need to be added to this process as an attachment. For example: related documents, pdf, csv"
          required: false
          schema:
            type: array
            example: ['share://123456789.pdf', 'share://987654321.csv']
      responses:
        '201':
          description: '201 response'
          content:
            application/json:
              examples:
                foo:
                  value: { '@id': 'http://data.lblod.info/processes/123456789' }
    patch:
      operationId: patchProcess
      summary: 'Update a process in your administrative unit.'
      tags:
        - Processes
      parameters:
        - name: '@id'
          in: body
          description: 'Uri of the process.'
          required: true
          schema:
            type: string
            example: 'http://data.lblod.info/processes/123456789'
        - name: title
          in: body
          description: 'Name for the process.'
          required: false
          schema:
            type: string
            example: 'Facturatie'
        - name: description
          in: body
          description: 'Describe what the process is about'
          required: false
          schema:
            type: string
            example: 'De officiële factuur wordt gegenereerd op basis van deze gegevens en vervolgens naar de klant verzonden ter betaling, wat de standaardcyclus afsluit.'
        - name: contact
          in: body
          description: 'Email of person that can be contacted about the process.'
          required: false
          schema:
            type: string
            example: 'contact@administrativeUnit.com'
        - name: linkedInventoryProcess
          in: body
          description: 'Inventory process URI that this process is related to.'
          required: false
          schema:
            type: string
            example: 'http://data.lblod.info/conceptual-processes/123456789'
        - name: users
          in: body
          description: 'List of administrative units that are also using this process. '
          required: false
          schema:
            type: array
            example:
              [
                'http://data.lblod.info/id/bestuurseenheden/123456789',
                'http://data.lblod.info/id/bestuurseenheden/987654321',
              ]
        - name: diagrams
          in: body
          description: "List of file URI's that need to be added to this process. For example: bpmn, visio"
          required: false
          schema:
            type: array
            example: ['share://123456789.bpmn', 'share://987654321.bpmn']
        - name: attachments
          in: body
          description: "List of file URI's that need to be added to this process as an attachment. For example: related documents, pdf, csv"
          required: false
          schema:
            type: array
            example: ['share://123456789.pdf', 'share://987654321.csv']
      responses:
        '200':
          description: '200 response'
    delete:
      operationId: deleteProcess
      summary: 'Delete a process in your administrative unit.'
      tags:
        - Processes
      parameters:
        - name: '@id'
          in: body
          description: 'Uri of the process.'
          required: true
          schema:
            type: string
            example: 'http://data.lblod.info/processes/123456789'
      responses:
        '204':
          description: '204 response'
  /processes/files:
    delete:
      operationId: deleteFileFromProcess
      summary: 'Delete a file from a process'
      tags:
        - Processes
      parameters:
        - name: '@id'
          in: body
          description: 'Uri of the process.'
          required: true
          schema:
            type: string
            example: 'http://data.lblod.info/processes/123456789'
        - name: 'fileUri'
          in: body
          description: 'Uri for the file'
          required: true
          schema:
            type: string
            example: 'share://123456789.bpmn'
      responses:
        '204':
          description: '204 response'
  /files:
    post:
      operationId: postFile
      summary: 'Uploading a new file'
      tags:
        - Files
      parameters:
        - name: 'file'
          in: body
          description: 'The file that you want to upload.'
          required: true
          schema:
            type: string
            example: 'share://123456789.bpmn'
      responses:
        '201':
          description: '201 response'
          content:
            application/json:
              examples:
                foo:
                  value: { '@id': 'share://123456789.bpmn' }
    delete:
      operationId: deleteFile
      summary: 'Delete a file in your administrative unit.'
      tags:
        - Files
      parameters:
        - name: '@id'
          in: body
          description: 'Uri of the file.'
          required: true
          schema:
            type: string
            example: 'share://123456789.bpmn'
      responses:
        '204':
          description: '204 response'
