# https://swagger.io/docs/specification/v3_0/data-models/data-models/
openapi: 3.0.0
info:
  title: 'Open Proces Huis'
  description: 'Manage your processes in OPH. Update existing or create processes in your administrative-unit.'
  version: 0.0.0
  contact:
    name: Support
    email: loketlokaalbestuur@vlaanderen.be
    url: https://abb-vlaanderen.gitbook.io/informatie-oph
externalDocs:
  description: Find out more about the API on Github
  url: https://github.com/lblod/vendor-api-openproceshuis
servers:
  - url: http://localhost/api/vendor
    description: Local server
  - url: https://dev.openproceshuis.lblod.info/api/vendor
    description: Development server
tags:
  - name: Processes
    description: Create and update actions on processes in Open Proces Huis
  - name: Files
    description: Uploading and deleting diagrams and attachments used in Open Proces Huis

paths:
  /processes:
    post:
      operationId: postProcess
      summary: 'Adding a new process to your administrative unit.'
      tags:
        - Processes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProcess'
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              examples:
                foo:
                  value: { '@id': 'http://data.lblod.info/processes/123456789' }
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    patch:
      operationId: patchProcess
      summary: 'Update a process in your administrative unit.'
      tags:
        - Processes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProcess'
      responses:
        '200':
          description: 'Ok'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    put:
      operationId: putProcess
      summary: 'Replace data of process in your administrative unit.'
      tags:
        - Processes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProcess'
      responses:
        '200':
          description: 'Ok'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    delete:
      operationId: deleteProcess
      summary: 'Delete a process in your administrative unit.'
      tags:
        - Processes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - '@id'
              properties:
                '@id':
                  type: string
                  description: 'Uri of the process.'
                  required: true
                  pattern: '^(https?://)[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*(/.*)?$'
            example:
              '@id': 'http://data.lblod.info/processes/123456789'
      responses:
        '204':
          description: 'No content'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /processes/files:
    delete:
      operationId: deleteFileFromProcess
      summary: 'Delete a file from a process'
      tags:
        - Processes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - '@id'
                - 'fileUri'
              properties:
                '@id':
                  type: string
                  description: 'Uri of the process.'
                  required: true
                  pattern: '^(https?://)[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*(/.*)?$'
                fileUri:
                  type: string
                  description: 'Uri of the file.'
                  required: true
            example:
              '@id': 'http://data.lblod.info/processes/123456789'
              fileUri: 'http://mu.semte.ch/services/file-service/files/123456789.bpmn'
      responses:
        '204':
          description: 'No content'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /files:
    post:
      operationId: postFile
      summary: 'Uploading a new file'
      tags:
        - Files
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The file that you want to upload.
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              examples:
                foo:
                  value:
                    {
                      '@id': 'http://mu.semte.ch/services/file-service/files/123456789.bpmn',
                    }
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    delete:
      operationId: deleteFile
      summary: 'Delete a file in your administrative unit.'
      tags:
        - Files
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - '@id'
              properties:
                '@id':
                  type: string
                  description: 'Uri of the file.'
                  pattern: '^(https?://)[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*(/.*)?$'
            example:
              '@id': 'http://mu.semte.ch/services/file-service/files/123456789.bpmn'
      responses:
        '204':
          description: 'No content'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  responses:
    UnauthorizedError:
      description: Unauthorized
  schemas:
    CreateProcess:
      required:
        - '@id'
        - title
      type: object
      properties:
        '@id':
          type: string
          description: 'Uri of the process.'
          example: 'http://data.lblod.info/processes/123456789'
          pattern: '^(https?://)[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*(/.*)?$'
        title:
          type: string
          description: 'Name for the process.'
          example: 'Facturatie'
        description:
          type: string
          description: 'Describe what the process is about.'
          example: 'The official invoice is generated based on this data and subsequently sent to the customer for payment, which concludes the standard cycle.'
        contact:
          type: string
          description: 'Email of person that can be contacted about the process.'
          example: 'contact@administrativeUnit.com'
        linkedInventoryProcess:
          type: string
          description: 'Inventory process URI that this process is related to.'
          example: 'http://data.lblod.info/conceptual-processes/123456789'
          pattern: '^(https?://)[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*(/.*)?$'
        users:
          type: array
          description: 'List of administrative units that are also using this process.'
          items:
            type: string
            pattern: '^(https?://)[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*(/.*)?$'
          example:
            [
              'http://data.lblod.info/id/bestuurseenheden/123456789',
              'http://data.lblod.info/id/bestuurseenheden/987654321',
            ]
        diagrams:
          type: array
          description: "List of file URI's that need to be added to this process. For example: bpmn, visio"
          items:
            type: string
            pattern: '^(https?://)[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*(/.*)?$'
          example:
            [
              'http://mu.semte.ch/services/file-service/files/123456789.bpmn',
              'http://mu.semte.ch/services/file-service/files/987654321.bpmn',
            ]
        attachments:
          type: array
          description: "List of file URI's that need to be added to this process as an attachment. For example: related documents, pdf, csv"
          items:
            type: string
            pattern: '^(https?://)[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*(/.*)?$'
          example:
            [
              'http://mu.semte.ch/services/file-service/files/123456789.pdf',
              'http://mu.semte.ch/services/file-service/files/987654321.csv',
            ]
    UpdateProcess:
      required:
        - '@id'
      type: object
      properties:
        '@id':
          type: string
          description: 'Uri of the process.'
          example: 'http://data.lblod.info/processes/123456789'
          pattern: '^(https?://)[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*(/.*)?$'
        title:
          type: string
          description: 'Name for the process.'
          example: 'Facturatie'
        description:
          type: string
          description: 'Describe what the process is about.'
          example: 'The official invoice is generated based on this data and subsequently sent to the customer for payment, which concludes the standard cycle.'
        contact:
          type: string
          description: 'Email of person that can be contacted about the process.'
          example: 'contact@administrativeUnit.com'
        linkedInventoryProcess:
          type: string
          description: 'Inventory process URI that this process is related to.'
          example: 'http://data.lblod.info/conceptual-processes/123456789'
          pattern: '^(https?://)[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*(/.*)?$'
        users:
          type: array
          description: 'List of administrative units that are also using this process.'
          items:
            type: string
            pattern: '^(https?://)[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*(/.*)?$'
          example:
            [
              'http://data.lblod.info/id/bestuurseenheden/123456789',
              'http://data.lblod.info/id/bestuurseenheden/987654321',
            ]
        diagrams:
          type: array
          description: "List of file URI's that need to be added to this process. For example: bpmn, visio"
          items:
            type: string
            pattern: '^(https?://)[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*(/.*)?$'
          example:
            [
              'http://mu.semte.ch/services/file-service/files/123456789.bpmn',
              'http://mu.semte.ch/services/file-service/files/987654321.bpmn',
            ]
        attachments:
          type: array
          description: "List of file URI's that need to be added to this process as an attachment. For example: related documents, pdf, csv"
          items:
            type: string
            pattern: '^(https?://)[a-zA-Z0-9-]+(.[a-zA-Z0-9-]+)*(/.*)?$'
          example:
            [
              'http://mu.semte.ch/services/file-service/files/123456789.pdf',
              'http://mu.semte.ch/services/file-service/files/987654321.csv',
            ]

security:
  - ApiKeyAuth: []
